# Create Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: my-app-namespace

---

# Deployment using the namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: my-app-namespace
  labels:
    app: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: us-central1-docker.pkg.dev/krisha-dev-459506/krisha-repo/react-app:__IMAGE_TAG__
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"

---

# Horizontal Pod Autoscaler using the namespace
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: react-app-hpa
  namespace: my-app-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-app-deployment
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90